name: twa-test
favicon: null
layout_spectrum: 0.5517258793115616
typography_spectrum: 0.4944083720911294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.18422343395650387
  lightness: 0.6110968051943928
  saturation: 0.8949193838052452
  rhythmicContrast: 0.4444458978250623
purpose: []
